class Decision:
    """
    Takes the args for the function, passes them to the event generated by the
    function

    This is basically a continuation monad
    """

    def __init__(self, args):
        self._args = args

    def __irshift__(self, func):
        """
        >>=
        Haskell-like notation for bind
        """
        func(self._args)
